{"ast":null,"code":"const {\n  processValidationErrors\n} = require(\"../errorUtilities/processValidationErrors\");\n\nfunction handleValidationError(err, req, res, next) {\n  if (!(err.name === \"ValidationError\")) return next(err);\n  res.status(400).json({\n    status: \"fail\",\n    name: \"validationError\",\n    //TODO i have changed case in error names to camel case in mongo they are capitalised is this the right decision.\n    message: err.message,\n    errors: processValidationErrors(err.errors)\n  });\n}\n\nfunction handleNotFoundError(err, req, res, next) {\n  if (!err.Status === 404) return next(err);\n  res.status(err.statusCode).json({\n    status: err.status,\n    message: err.message\n  });\n}\n\nfunction handleError(err, req, res, next) {\n  console.error(err);\n  if (res.headersSent) return next(err);\n  res.status(500).json({\n    error: \"Internal Error\"\n  });\n}\n\nmodule.exports = {\n  handleValidationError,\n  handleNotFoundError,\n  handleError\n};","map":{"version":3,"sources":["/home/gregorian/calendar-ui/api/controllers/errorControllers.js"],"names":["processValidationErrors","require","handleValidationError","err","req","res","next","name","status","json","message","errors","handleNotFoundError","Status","statusCode","handleError","console","error","headersSent","module","exports"],"mappings":"AAAA,MAAM;AACJA,EAAAA;AADI,IAEFC,OAAO,CAAC,2CAAD,CAFX;;AAIA,SAASC,qBAAT,CAA+BC,GAA/B,EAAoCC,GAApC,EAAyCC,GAAzC,EAA8CC,IAA9C,EAAoD;AAClD,MAAI,EAAEH,GAAG,CAACI,IAAJ,KAAa,iBAAf,CAAJ,EAAuC,OAAOD,IAAI,CAACH,GAAD,CAAX;AACvCE,EAAAA,GAAG,CAACG,MAAJ,CAAW,GAAX,EAAgBC,IAAhB,CAAqB;AACnBD,IAAAA,MAAM,EAAE,MADW;AAEnBD,IAAAA,IAAI,EAAE,iBAFa;AAEM;AACzBG,IAAAA,OAAO,EAAEP,GAAG,CAACO,OAHM;AAInBC,IAAAA,MAAM,EAAEX,uBAAuB,CAACG,GAAG,CAACQ,MAAL;AAJZ,GAArB;AAMD;;AAED,SAASC,mBAAT,CAA6BT,GAA7B,EAAkCC,GAAlC,EAAuCC,GAAvC,EAA4CC,IAA5C,EAAkD;AAChD,MAAI,CAACH,GAAG,CAACU,MAAL,KAAgB,GAApB,EAAyB,OAAOP,IAAI,CAACH,GAAD,CAAX;AACzBE,EAAAA,GAAG,CAACG,MAAJ,CAAWL,GAAG,CAACW,UAAf,EAA2BL,IAA3B,CAAgC;AAC9BD,IAAAA,MAAM,EAAEL,GAAG,CAACK,MADkB;AAE9BE,IAAAA,OAAO,EAAEP,GAAG,CAACO;AAFiB,GAAhC;AAID;;AAED,SAASK,WAAT,CAAqBZ,GAArB,EAA0BC,GAA1B,EAA+BC,GAA/B,EAAoCC,IAApC,EAA0C;AACxCU,EAAAA,OAAO,CAACC,KAAR,CAAcd,GAAd;AACA,MAAIE,GAAG,CAACa,WAAR,EAAqB,OAAOZ,IAAI,CAACH,GAAD,CAAX;AACrBE,EAAAA,GAAG,CAACG,MAAJ,CAAW,GAAX,EAAgBC,IAAhB,CAAqB;AAAEQ,IAAAA,KAAK,EAAE;AAAT,GAArB;AACD;;AAEDE,MAAM,CAACC,OAAP,GAAiB;AACflB,EAAAA,qBADe;AAEfU,EAAAA,mBAFe;AAGfG,EAAAA;AAHe,CAAjB","sourcesContent":["const {\n  processValidationErrors,\n} = require(\"../errorUtilities/processValidationErrors\");\n\nfunction handleValidationError(err, req, res, next) {\n  if (!(err.name === \"ValidationError\")) return next(err);\n  res.status(400).json({\n    status: \"fail\",\n    name: \"validationError\", //TODO i have changed case in error names to camel case in mongo they are capitalised is this the right decision.\n    message: err.message,\n    errors: processValidationErrors(err.errors),\n  });\n}\n\nfunction handleNotFoundError(err, req, res, next) {\n  if (!err.Status === 404) return next(err);\n  res.status(err.statusCode).json({\n    status: err.status,\n    message: err.message,\n  });\n}\n\nfunction handleError(err, req, res, next) {\n  console.error(err);\n  if (res.headersSent) return next(err);\n  res.status(500).json({ error: \"Internal Error\" });\n}\n\nmodule.exports = {\n  handleValidationError,\n  handleNotFoundError,\n  handleError,\n};\n"]},"metadata":{},"sourceType":"script"}